In [1]:
import numpy as np

In [7]:
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,2)
print(a)
print(b)
a.shape=(3,2)
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [12]:
a=np.arange(24)
a.shape=(2,4,3)
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [14]:
w = np.random.normal(0, 1, 3)
print(w)

[ 0.76902026 -0.49432514 -2.556049  ]


In [15]:
x=np.linspace(10,20,6)
print(x)

[10. 12. 14. 16. 18. 20.]


## Linked List (MAM)

In [ ]:
class Node:
    def __init__(self,data):
        self.data = data
        self.next = None
       
    def get_Next(self):
        return self.next
   
    def get_Data(self):
        return self.data
   
class Linked_List:
    def __init__(self):
        self.head = None
       
    def insertion_beg(self,d):
        new_node = Node(d)
        new_node.next = self.head
        self.head = new_node
    
    

    def traverse(self):
        current = self.head
        count = 0
        print("Linked List:")
        while current != None:
            print(current.data)
            count += 1
            current = current.get_Next()
        print("\nLength:",count)        
       
llist = Linked_List()
llist.head = Node(5)
n2 = Node(6)
n3 = Node(7)
llist.head.next = n2
n2.next = n3
llist.insertion_beg(2)
llist.traverse()    



### Insertion beginning

In [10]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll1:
    def __init__(self):
        self.start=None
    def ins_beg(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                n.next=self.start
                self.start=n
                
    def length(self):
        c=0
        q=self.start
        while(q!=None):
            c+=1
            q=q.next
        return c
    
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll1()
p.ins_beg()

p.traverse()

Enter no of elements:
5
Enter element
5
Enter element
4
Enter element
3
Enter element
2
Enter element
1
5
1
2
3
4
5


### Insertion ending

In [5]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
    
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll2()
p.ins_end()
p.traverse()

Enter no of elements:
4
Enter element
1
Enter element
2
Enter element
3
Enter element
4
1
2
3
4


### Insertion Between

In [4]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
                
    def length(self):
        c=0
        q=self.start
        while(q!=None):
            c+=1
            q=q.next
        return c
    
    def ins_bet(self):
        print("enter position")
        pos=int(input())
        print("Enter element")
        item=int(input())
        ptr=self.start
        prev=self.start
        while(pos>0):
            prev=ptr
            ptr=ptr.next;
            pos-=1
            
        p=node(item)
        if ptr==self.start:
            p.next=self.start
            self.start=p
            
        elif ptr==None:
            prev.next=p
        else:
            prev.next=p
            p.next=ptr
            
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll()
p.ins_end()
p.ins_bet()
p.traverse()

Enter no of elements:
3
Enter element
1
Enter element
2
Enter element
3
enter position
3
Enter element
4
1
2
3
4


### Deletion between

In [7]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
                
    def length(self):
        c=0
        q=self.start
        while(q!=None):
            c+=1
            q=q.next
        return c
    
    def delete(self,x):
        ptr=self.start
        prev=self.start
        while(ptr!=None and ptr.data!=x):
            prev=ptr
            ptr=ptr.next
        if ptr==None:
            print("Nothing to delete")
        elif ptr==self.start:
            self.start=ptr.next
            ptr.next=None
            ptr=None
        elif ptr.next==None:
            prev.next=None
            ptr=None
        else:
            prev.next=ptr.next
            ptr.next=None
            ptr=None
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll2()
p.ins_end()
print("Enter element to be deleted")
p.delete(int(input()))
p.traverse()

Enter no of elements:
4
Enter element
1
Enter element
2
Enter element
3
Enter element
4
Enter element to be deleted
4
1
2
3


### Insertion in a sorted linked list

In [3]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_sort(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                prev=self.start
                while(ptr!=None and ptr.data<n.data):
                    prev=ptr
                    ptr=ptr.next
                if ptr==self.start:
                    n.next=ptr
                    self.start=n
                elif ptr==None:
                    prev.next=n
                else:
                    n.next=ptr
                    prev.next=n
    
    def length(self):
        c=0
        q=self.start
        while(q!=None):
            c+=1
            q=q.next
        return c
    
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll2()
p.ins_sort()
p.traverse()

Enter no of elements:
6
Enter element
5
Enter element
3
Enter element
6
Enter element
1
Enter element
4
Enter element
2
1
2
3
4
5
6


### Reversing nodes of a single linked list

In [8]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
    
    def length(self):
        c=0
        q=self.start
        while(q!=None):
            c+=1
            q=q.next
        return c
    
    def reverse(self):
        pn=None
        cn=self.start
        while(cn!=None):
            nn=cn.next
            cn.next=pn
            pn=cn
            cn=nn
        rev=pn
        while(rev.next!=None):
            print(rev.data)
            rev=rev.next
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll2()
p.ins_end()
p.reverse()
p.traverse()

Enter no of elements:
5
Enter element
1
Enter element
2
Enter element
3
Enter element
4
Enter element
5
5
4
3
2
1


### Reversing Nodes of LL (Recursion)

In [1]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
      
def traverse(start):
        current=start
        while(current!=None):
            print(current.data)
            current=current.next
def recReverse(start):
        if start==None:
            return None
        elif start.next==None:
            return start
        finalhead=recReverse(start.next)
        start.next.next=start
        start.next=None
        return finalhead
p=ll2()
p.ins_end()
traverse(p.start)
l=recReverse(p.start)
traverse(l)

Enter no of elements:
4
Enter element
1
Enter element
2
Enter element
3
Enter element
4
1
2
3
4
4
3
2
1


### Reverse k elements of a list

In [5]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
def traverse(start):
        current=start
        while(current!=None):
            print(current.data)
            current=current.next
def kreverse(start,k):
    if start==None or k<=1:
        return start
    elif start.next==None:
        return start
    prev=start
    curr=start.next
    i=1
    prev.next=None
    while curr and i<k:
        next=curr.next
        curr.next=prev
        prev=curr
        curr=next
        i+=1
    start.next=kreverse(curr,k)
    return prev

p=ll2()
p.ins_end()
a=kreverse(p.start,3)
traverse(a)

Enter no of elements:
5
Enter element
1
Enter element
2
Enter element
3
Enter element
4
Enter element
5
3
2
1
5
4


### 1# Check Palindrome...**DOUBT

In [ ]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
                
    def length(self):
        c=0
        q=self.start
        while(q!=None):
            c+=1
            q=q.next
        return c
    
    
    def palindrome(self):
        l=self.length()
        if l%2!=0:
            print("Hi Not a Palindrome")
        else:
            op=self.start
            f=0
            start1=None
            while(op!=None):
                p=node(op.data)
                if start1==None:
                    start1=p
                else:
                    p.next=start1
                    start1=p
            op=self.start
            fp=start1
            while(op!=None):
                if op.data==fp.data:
                    continue
                else:
                    f=1
                    break
                fp=fp.next
                op=op.next
            if f==1:
                print("Not a palindrome")
            else:
                print("Palindrome")
        
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll2()
p.ins_end()
p.palindrome()

p.traverse()

Enter no of elements:
6
Enter element
1
Enter element
2
Enter element
3
Enter element
4
Enter element
5
Enter element
6


### Merge 2 sorted Linked List

In [4]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
    
def traverse(start):
        current=start
        while(current!=None):
            print(current.data)
            current=current.next
def merge(h1,h2):
    if h1==None:
        return h2
    if h2==None:
        return h2
    if h1.data<=h2.data:
        head=h1
        h1=h1.next
    else:
        head=h2
        h2=h2.next
    curr=head
    while (h1 and h2):
        if h1.data<=h2.data:
            curr.next=h1
            h1=h1.next
        else:
            curr.next=h2
            h2=h2.next
        curr=curr.next
    if h1==None:
        curr.next=h2
    else:
        curr.next=h1
    return head
  
p=ll2()
print("Enter elements of first list")
p.ins_end()
q=ll2()
print("Enter elements of second list")
q.ins_end()
z=merge(p.start,q.start)
traverse(z)

Enter elements of first list
Enter no of elements:
4
Enter element
2
Enter element
5
Enter element
6
Enter element
8
Enter elements of second list
Enter no of elements:
3
Enter element
1
Enter element
4
Enter element
7
1
2
4
5
6
7
8


### Mergesort LL

In [ ]:

class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
    
def traverse(start):
        current=start
        while(current!=None):
            print(current.data)
            current=current.next
def midpoint(start):
        p=start
        t=0
        while(p!=None):
            t+=1
            p=p.next
        p=start
        for i in range(1,(t+1)//2):
            p=p.next
        return p
def mergeSort(head):
    if head==None:
        return None
    if head.next==None:
        return head
    mid=midpoint(head)
    head2=mid.next
    mid.next=None
    head=mergeSort(head)
    head2=mergeSort(head2)
    head=merge(head,head2)
    return head
def merge(head1,head2):
    if head1==None:
        return head2
    if head2==None:
        return head1
    if head1.data<=head2.data:
        head=head1
        head1=head1.next
    else:
        head=head2
        head2.next
    curr=head
    while(head1 and head2):
        if head1.data<=head2.data:
            curr.next=head1
            head1=head1.next
        else:
            curr.next=head2
            head2=head2.next
        curr=curr.next
    if head1==None:
        curr.next=head2
    else:
        curr.next=head1
    return head
p=ll2()
p.ins_end()
q=mergeSort(p.start)
traverse(q)

Enter no of elements:
3
Enter element
2
Enter element
3
Enter element
1


### Insertion between in DLL

In [8]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
        self.prev=None
class ll:
    def __init__(self):
        self.start=None
        self.tail=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
                self.tail=n
            else:
                self.tail.next=n
                n.prev=self.tail
                self.tail=self.tail.next
                
    
    def ins_bet(self):
        print("enter position")
        pos=int(input())
        print("Enter element")
        item=int(input())
        ptr=self.start
        pre=self.start
        while(pos>0):
            pre=ptr
            ptr=ptr.next;
            pos-=1
            
        p=node(item)
        if ptr==self.start:
            p.next=ptr
            ptr.prev=p
            self.start=p
            
        elif ptr==None:
            pre.next=p
            p.prev=pre
            self.tail=self.tail.next
        else:
            p.next=ptr
            ptr.prev=p
            pre.next=p
            p.prev=pre
            
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll()
p.ins_end()
p.ins_bet()
p.traverse()

Enter no of elements:
4
Enter element
1
Enter element
2
Enter element
3
Enter element
4
enter position
4
Enter element
7
1
2
3
4
7


### Deletion in DLL

In [1]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
        self.prev=None
class ll:
    def __init__(self):
        self.start=None
        self.tail=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
                self.tail=n
            else:
                self.tail.next=n
                n.prev=self.tail
                self.tail=self.tail.next
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
    def delete(self):
        x=int(input("Enter number to be deleted"))
        ptr=self.start
        pre=self.start
        while(ptr!=None and ptr.data!=x):
            pre=ptr
            ptr=ptr.next
        skip=ptr.next
        if ptr==None:
            print("No Deletion")
        elif ptr==self.start:
            self.start=ptr.next
            skip.prev=None
            ptr.next=None
            ptr=None
        elif ptr.next==None:
            pre.next=None
            ptr.prev=None
            ptr=None
        else:
            pre.next=ptr.next
            skip.prev=pre
            ptr.next=None
            ptr=None
p=ll()
p.ins_end()
p.delete()
p.traverse()

Enter no of elements:
4
Enter element
1
Enter element
2
Enter element
3
Enter element
4
Enter number to be deleted1
2
3
4


### Insertion in a CLL

In [18]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.last=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.last==None:
                self.last=n
                n.next=self.last
            else:
                n.next=self.last.next
                self.last.next=n
                self.last=self.last.next
    def ins_bet(self):
        pos=int(input("Enter position"))
        x=int(input("Enter element"))
        ptr=self.last.next
        prev=self.last.next
        while(pos>0):
            prev=ptr
            ptr=ptr.next
            pos-=1
        p=node(x)
        if ptr==self.last.next:
            p.next=ptr
            self.last.next=p
        elif ptr==self.last:
            p.next=ptr.next
            ptr.next=p
            self.last=p
        else:
            p.next=prev.next
            prev.next=p
            
    
    def traverse(self):
        current=self.last.next
        while(current):
            print(current.data)
            current=current.next
            if current==self.last.next:
                break
            
p=ll2()
p.ins_end()
p.ins_bet()
p.traverse()

Enter no of elements:
3
Enter element
1
Enter element
2
Enter element
3
Enter position2
Enter element8
1
2
3
8


### Deletion in CLL

In [4]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll:
    def __init__(self):
        self.last=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.last==None:
                self.last=n
                n.next=self.last
            else:
                n.next=self.last.next
                self.last.next=n
                self.last=self.last.next
    def traverse(self):
        current=self.last.next
        while(current):
            print(current.data)
            current=current.next
            if current==self.last.next:
                break
    def delete(self):
        x=int(input("Enter number to be deleted"))
        ptr=self.last.next
        pre=self.last.next
        while(ptr and ptr.data!=x):
            pre=ptr
            ptr=ptr.next
            if ptr==self.last.next:
                break

        if ptr==self.last.next:
            self.last.next=ptr.next
            ptr.next=None
            ptr=None
        elif ptr==self.last:
            pre.next=ptr.next
            self.last=pre
            ptr.next=None
            ptr=None
        else:
            pre.next=ptr.next
            ptr.next=None
            ptr=None
p=ll()
p.ins_end()
p.delete()
p.traverse()

Enter no of elements:
3
Enter element
1
Enter element
2
Enter element
3
Enter number to be deleted3
1
2


### Bubble Sort in LL

In [2]:
class node:
    def __init__(self,data):
        self.data=data
        self.next=None
class ll2:
    def __init__(self):
        self.start=None
    def ins_end(self):
        print("Enter no of elements:")
        for i in range(int(input())):
            print("Enter element")
            n=node(int(input()))
            n.next=None
            if self.start==None:
                self.start=n
            else:
                ptr=self.start
                while(ptr.next!=None):
                    ptr=ptr.next
                ptr.next=n
    def bubbleSort(self):
        if self.start==None or self.start.next==None:
            return self.start
        swap=True
        while swap:
            swap=False
            prev=None
            curr=self.start
            nex=curr.next
            while nex:
                if curr.data>nex.data:
                    swap=True
                    if prev:
                        prev.next=nex
                    else:
                        self.start=nex
                    curr.next=nex.next
                    nex.next=curr
                    prev=nex
                else:
                    prev=curr
                curr=prev.next
                nex=curr.next
    
    def traverse(self):
        current=self.start
        while(current!=None):
            print(current.data)
            current=current.next
p=ll2()
p.ins_end()
p.bubbleSort()
p.traverse()

Enter no of elements:
4
Enter element
3
Enter element
2
Enter element
1
Enter element
4
1
2
3
4


### 